# Generated by Django 5.0.1 on 2024-02-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="My Freakin' Awesome Blog!", max_length=255),
        ),
    ]
