# Generated by Django 5.0.1 on 2024-02-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog1', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
