# Generated by Django 5.0.1 on 2024-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog1', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click above link to see the blog', max_length=255),
        ),
    ]
