# Generated by Django 5.0.1 on 2024-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog1', '0008_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headewr_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
