# Generated by Django 5.0.1 on 2024-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog1', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
